### ISSUE TITLE
Kanban board

### ISSUE THREAD

**Issue by biruk-bereka** [biruk-bereka/Recipe-app#10]
## In this issue: 
   - We created a Kanban board for our project
   - We created different cards on the Kanban board as required on  project requirement
   - We assigned all the cards fairly

Two team members: @biruk-bereka  and @NelsonAraujo93 
Project link: https://github.com/users/biruk-bereka/projects/4/views/1

**Comment by cynthiainga** [comment]
Hi @biruk-bereka & @NelsonAraujo93, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights

- [ ] Descriptive issue ✔️ 
- [ ] All cards are assigned ✔️ 
- [ ] All cars have a descriptive title, number of points in the [Xpt] prefix, and a description of the task ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
